# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-01 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_forms', '0005_formfield_field_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdefinition',
            name='email_reply_to',
            field=models.CharField(blank=True, help_text='Reply to e-mail header. Use form field values by inserting placeholders of field names, e.g. "{my name field} <{my email field}>"', max_length=255, verbose_name='Reply to'),
        ),
        migrations.AlterField(
            model_name='formdefinition',
            name='email_subject',
            field=models.CharField(blank=True, help_text='Use form field values by inserting placeholders of field names, e.g. "{my subject}"', max_length=255, verbose_name='Email Subject'),
        ),
    ]
