# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_forms', '0005_formfield_field_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='css_class',
            field=models.CharField(blank=True, max_length=100, verbose_name='CSS class'),
        ),
    ]
